In [8]:
import numpy as np

## Numpy Slicing of Vectors

In [6]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[3:6]

array([4, 5, 6])

In [5]:
# no of steps is 2
arr[3:10:2]

array([ 4,  6,  8, 10])

## Numpy Indexing and Slicing of Matrix

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Slicing a Diagonal Portion, [[2,3],[7,8]]

In [11]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

### For getting a Specific Column, [2,7,12,17,22,27]

In [13]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [19]:
arr = np.arange(1,31)

### Taking only Even Numbers (Boolean Indexing)

In [20]:
arr[ arr % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])