In [1]:
import numpy as np

# Array Operations

### Arithmetic Operations

In [7]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [8]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

In [13]:
arr = np.array([1,2,3,4,5,6])

In [14]:
arr + 10

array([11, 12, 13, 14, 15, 16])

### Deep and Shallow copy

In [29]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [31]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
# directly assigning just creates shallow copy but .copy() creates deep copy
b = a.copy()
b[0] = 3

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
b

array([ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix operations

In [37]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [40]:
B

array([[5, 6],
       [7, 8]])

In [42]:
# multiplication by corresponding number
A * B

array([[ 5, 12],
       [21, 32]])

In [43]:
# actual matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [45]:
# Transpose of Matrix
A.T

array([[1, 3],
       [2, 4]])

### Advance Array Maniipulation

In [49]:
A

array([[1, 2],
       [3, 4]])

In [50]:
B

array([[5, 6],
       [7, 8]])

### Stacking Array

In [54]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [55]:
# vertical stack, takes one arg so passed as tuple
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
# horizontal stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [60]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]