In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [8]:
np.array(a)

array([1. , 2. , 3.5])

In [9]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# normalisation, where random values in [0,1]
np.random.rand(5)

array([0.38520647, 0.51560055, 0.14220144, 0.2901492 , 0.26764465])

In [23]:
# standardization, where randome values in [-3,3]
np.random.randn(10)

array([-0.59675493, -0.22582647,  1.17784222, -0.423789  ,  1.13924222,
       -0.89477534,  0.86073861, -1.09381857, -0.16760458, -0.43903413])

In [26]:
np.random.randint(9)

6

In [29]:
np.random.randint(10,20,10)

array([14, 12, 16, 16, 12, 11, 11, 15, 12, 17])

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape

(3, 3)

In [33]:
arr.size

9

In [34]:
arr.dtype

dtype('int64')

In [35]:
arr.min()

np.int64(1)

In [36]:
arr.max()

np.int64(9)

In [37]:
arr.sum()

np.int64(45)

In [39]:
# row sum => axis = 1
# col sum => axis = 0
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [40]:
arr.mean()

np.float64(5.0)

In [41]:
arr.std()

np.float64(2.581988897471611)

In [42]:
# index of maximum element
arr.argmax()

np.int64(8)

In [43]:
arr.argmin()

np.int64(0)

In [44]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
# reshapes the 1-d array to 2-d array with shape as m x n, m = 5, n = 6k
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])